# 

## Question

## Answer

It did.

When passed as an argument to the mess_with_demographics function, the object referenced by munsters is the same object referenced by the local variable demo_dict inside the function.

## Solution

Spot will find himself in the "dog house" for this one. The family's data is in shambles now.

Why? In Python, dictionaries are mutable, and when passed to a function, a reference to the dictionary is passed, not a copy. Thus, Spot's demo_dict starts off pointing to the munsters object. As a result, the changes made within the function directly affect the munsters dictionary. The key aspect here is that the nested dictionaries (the individual family members' data) are the ones being mutated. Each family member's dictionary ({"age": x, "gender": y}) is accessed and modified. Since these nested dictionaries are part of the larger munsters dictionary, the changes are reflected in the original data structure.

His program could replace that with some other object, and the family's data would be safe. However, in this case, the program doesn't reassign demo_dict; it just uses it, as-is. Thus, the object that gets changed by the function is the munsters object.

## Reflection


```python
munsters = {
    "Herman": {"age": 32, "gender": "male"},
    "Lily": {"age": 30, "gender": "female"},
    "Grandpa": {"age": 402, "gender": "male"},
    "Eddie": {"age": 10, "gender": "male"},
    "Marilyn": {"age": 23, "gender": "female"},
}

# bar = munsters["Herman"]
# print(id(bar))
# print(id(munsters["Herman"]))

def mess_with_demographics(demo_dict):
    print(id(demo_dict))
    for key, value in demo_dict.items():
        print(f"{id(key)=}")
        print(f"{id(value)=}")

print(id(munsters))
mess_with_demographics(munsters)
```